services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
      - microservice-net
    restart: unless-stopped # it means automatically restart container when stopped

  mongodb:
    container_name: ms_mongo_db
    image: mongo
    # Can set this way as well
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo:/data
    ports:
      - 27018:27017

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  microservice-net:
    driver: bridge

volumes:
  postgres:
  mongo: