server:
  port: 8092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/order
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    customer-url: http://localhost:8090/api/v1/customers
    product-url: http://localhost:8091/api/v1/products
    payment-url: http://localhost:8093/api/v1/customers